sudo: required
language: python
python:
  - "2.7"
services:
- docker
before_install:
- docker pull golang:1.6
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - pip install docker-cloud

script:
- make test
- make release

after_success:
- make docker
- docker-cloud service ps

env:
  global:
  - secure: Xu3k/uU22TWcqYmK0NMOFZ+P1HimlMVKdOE3l5ImGUd3SSeL4MIKNVjEr2RKjqmkGVC3L/W+2qN8SDcxgxN9MhhOl5OJPsCYt5WMY0lxyNuBdHsjlJbpyblbQ42IPZJfJvjPxbhP/JqtDU3m7cCEsvy7XuGmkpbj0E2UvGFC63YHKTHh0/OHPgutmhxcCAz/oKhf6S6VTQ0WgS1/BrD3po4cERftlQzBVslNm/gdSgM7iNvflnPEWV5oUGPQfRQhWKgQ9caGMzd/w3MGR5wwl+Na3i2BW4cOs5ZvTF/JUIkuCH7y/QVD+pbhrgxE/A0pFKb/qEUamYIw8Rwi7VXMAmfkgq0REe/eHzqbII2qaEzZGx7+/C3nch3GrLUNwlot46YhZTThPURMHmwwjrrFO8Pn6c/xrOakrwbJeoeX8yDwMDN0Ma4+x0+cQXQFpouzsDoypqIqUJL9fsr2O/lg0QrPD7OZJ9D9UuQLOSvpKE7fNbUTh7WKEbTvWI1Avym0kc/kCWU1ZVSoGlKiT7VfSsxA6iqvoHnfImXUf+YuMO+EvjoWjoTDjHkUsm+sP097lze8MfCzoLNHSRE/3dZlLwrhHCB2Slsgmix5T3O2Skjat5yXLlIrwVNnD45X/cM0PDaSC9uHOuKMoeyN0TMml/qKG6RkB/yQ/JEulkRR6TQ=
  - secure: IGOgoMYSWPflRbV4Fug2v1buWnE37CXu57B7BLTMrfW5ZXB+RFNa1i1pU0jgKFD5MIzzfT5Kf5tu/rsbsxWZdgIIEU99VWUzUe1o06bVpFAWBl1KDZZr0DYH68X3ulqpMxVW5MdIK2zBKYdU167rDSASP2F/eKrXqTAGAboTDKiBy/VGrxygCnFALPkJcXDRpXWAXRRhVGYO0HjGHvLJNrfLnk/selWbDb5on57kTkY3crYTrfJxgo7Hm1L+XTIuA9LFJ62p/VhvrXiHXwNdvXx/qJh22T+CekMWUEzgkpJ4aBjKPUeHTcGdzGBvCnwUxDZoKw1MtSR0fdm1mNSJd6lygs1573U1dqVrEtHejHbFMT+o2HZgLH1P1QVCaWcbTTzvPZXJ25H8UcrGtriPFwJ+9YLHhrIQSK1RuvqHJnq3hAiIa5CYZqspHrAit6cNUcVAATl5nUBukCrfOEM/fopmd0aGm/WOsKVLMs239dVnv8lsBbqWqI+E3UWKoSQwen1plkmAZOfK20Gc8yi7R3Lao4Q6Ly70oJpMlTrp65O0ww+yoUg/MxMfj68cshmewKl89NeLtIJvaIaUTQZGJXS/2md7Dj+0fNVQSYwnEvB9n7moJ+P+qduzRCGKzYPTSc1SVxEUU3Yl5oZm4RwASQLU6A0gQmH4X6k+yfybda0=
  - secure: wG5QRD5QcUHXQUkigpcMFIX3RMUUO1fpDkkTO8v2aeIQ8+t9DEiDXCeJtmNIoBKNatv0Sk3FjJoE0/otzLKHBMwsugdHETuDyiy+C3Z6kEcAdsjWr7tf6N5qg6xFL5K0r9BCMTg27AGLJjygzXum2VkQ/CtJuqz8rs91xCfQVwTpogp6Z6KfYgbQu51qRZKtMdNBM/Gz9p9Aq6nnRkccEjoM/3XMyDjn+cbwsKnEhlwL+24Tjn/mGJbxiwR802vR/f1yEsiUML/ajtnBnVtqwNbq7EkqbaN+EtdmA9klB6KVx9sVk18Wsj9gcIm6dP1TAd1JyegDGRA/ouCEGNB2x4CoXxzCPwqy2MoFTt9cP10TiQVI3Y4kdMkCbuCdR+IwPQ9HgLwXxQFyGdUDZQgpaBl1WLIWLB88czzZ0w0qBIDPvWI7yzu+cArZlVPVt1kTlKvj4APGpAF++/n7JBRY9CQ5hBMOM0j8FYEbqxgWdcIZgq+xRW/y+ZMbEeWrL4YKaZuhHyZXgJyCkHwuj87H7IKAUjRhkizTz6pXf+0/N9j3sCZLpQtOTv8Fn6WlBzF/T6NiqBQ6sGlJpN8yrGTiSD7yR3OQwI6If4HADo5PN8Xr9KwSl3dc4T9Ew+MqJhYG4jGbm/S0r8gMnud5grjyKb4o7FErmYonSvH4YeS47Hs=
